# Generated by Django 5.1.7 on 2025-04-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_fornecedor_cnpj_fornecedor_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
    ]
