# Generated by Django 5.1.7 on 2025-04-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_devolucao_data_atualizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucao',
            name='data_atualizacao',
        ),
        migrations.AlterField(
            model_name='venda',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='inventario.promocao'),
        ),
    ]
