# Generated by Django 5.1.7 on 2025-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_devolucao_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('entrega', 'Entrega'), ('retirada', 'Retirada'), ('loja', 'Loja')], default='retirada', max_length=10, verbose_name='Tipo de Venda'),
        ),
    ]
