# Generated by Django 5.1.7 on 2025-05-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_venda_tipo_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('concluida', 'Concluída'), ('devolvida', 'Devolvida')], default='concluida', max_length=30, verbose_name='Status da Venda'),
        ),
    ]
